In [1]:
import numpy as np
import pandas as pd

In [2]:
traindata=np.loadtxt("Cyclepowertrain.csv", delimiter = ",")
traindata

array([[   8.58,   38.38, 1021.03,   84.37,  482.26],
       [  21.79,   58.2 , 1017.21,   66.74,  446.94],
       [  16.64,   48.92, 1011.55,   78.76,  452.56],
       ...,
       [  29.8 ,   69.34, 1009.36,   64.74,  437.65],
       [  16.37,   54.3 , 1017.94,   63.63,  459.97],
       [  30.11,   62.04, 1010.69,   47.96,  444.42]])

In [3]:
testdata=np.loadtxt("Cyclepowertest.csv", delimiter = ",")
testdata

array([[  11.95,   42.03, 1017.58,   90.89],
       [  12.07,   38.25, 1012.67,   81.66],
       [  26.91,   74.99, 1005.64,   78.98],
       ...,
       [  24.32,   66.25, 1009.09,   91.89],
       [  23.49,   42.8 , 1013.96,   65.31],
       [  21.76,   60.27, 1018.96,   85.06]])

In [4]:
trainx=traindata[:,:-1]
trainy=traindata[:,-1]

In [5]:
from sklearn import preprocessing
scale=preprocessing.StandardScaler()

In [6]:
trainxscale=scale.fit_transform(trainx)
testxscale=scale.fit_transform(testdata)

In [7]:
traindf=pd.DataFrame(trainxscale)
testdf=pd.DataFrame(testxscale)

In [8]:
traindf.columns=['#T','V','AP','RH']
testdf.columns=['#T','V','AP','RH']
traindf,testdf

(            #T         V        AP        RH
 0    -1.478275 -1.247642  1.302211  0.758625
 1     0.289012  0.306798  0.661749 -0.446922
 2    -0.399976 -0.421013 -0.287207  0.375011
 3     1.572001  1.335770 -0.686238 -0.879086
 4    -1.395329 -1.118236  0.634923  1.311822
 ...        ...       ...       ...       ...
 7171 -1.379274 -1.298620  1.488313  0.424928
 7172 -1.127761 -1.012358  1.406160 -0.778567
 7173  1.360622  1.180483 -0.654383 -0.583683
 7174 -0.436097  0.000929  0.784141 -0.659585
 7175  1.402095  0.607960 -0.431395 -1.731106
 
 [7176 rows x 4 columns],
             #T         V        AP        RH
 0    -1.051800 -0.980329  0.739403  1.203540
 1    -1.035547 -1.280899 -0.098504  0.568089
 2     0.974385  1.640508 -1.298194  0.383580
 3     0.117049 -1.179119 -1.291368 -0.779234
 4    -0.397624 -1.364390 -0.217961 -0.307637
 ...        ...       ...       ...       ...
 2387  1.323820  1.220665 -0.666778 -1.174413
 2388  1.080028  0.873181  0.181367 -1.846353
 2389 

In [9]:
data=pd.concat([traindf,testdf],axis=0,ignore_index=True)
data

#T         V        AP        RH
0    -1.478275 -1.247642  1.302211  0.758625
1     0.289012  0.306798  0.661749 -0.446922
2    -0.399976 -0.421013 -0.287207  0.375011
3     1.572001  1.335770 -0.686238 -0.879086
4    -1.395329 -1.118236  0.634923  1.311822
...        ...       ...       ...       ...
9563  1.323820  1.220665 -0.666778 -1.174413
9564  1.080028  0.873181  0.181367 -1.846353
9565  0.623595  0.945541 -0.709441  1.272387
9566  0.511179 -0.919102  0.121639 -0.557549
9567  0.276868  0.470037  0.974904  0.802166

[9568 rows x 4 columns]

In [10]:
data['TT'] = data['#T'] ** 2
data['VV'] = data['V'] ** 2
data['APAP'] = data['AP'] ** 2
data['RHRH'] = data['RH'] ** 2
data['TV'] = data['#T'] * data['V']
data['TAP'] = data['#T'] * data['AP']
data['TRH'] = data['#T'] * data['RH']
data['VAP'] = data['V'] * data['AP']
data['VRH'] = data['V'] * data['RH']
data['APRH'] = data['AP'] * data['RH']
data


#T         V        AP        RH        TT        VV      APAP  \
0    -1.478275 -1.247642  1.302211  0.758625  2.185296  1.556610  1.695753   
1     0.289012  0.306798  0.661749 -0.446922  0.083528  0.094125  0.437912   
2    -0.399976 -0.421013 -0.287207  0.375011  0.159980  0.177252  0.082488   
3     1.572001  1.335770 -0.686238 -0.879086  2.471186  1.784283  0.470923   
4    -1.395329 -1.118236  0.634923  1.311822  1.946942  1.250451  0.403128   
...        ...       ...       ...       ...       ...       ...       ...   
9563  1.323820  1.220665 -0.666778 -1.174413  1.752500  1.490023  0.444593   
9564  1.080028  0.873181  0.181367 -1.846353  1.166460  0.762446  0.032894   
9565  0.623595  0.945541 -0.709441  1.272387  0.388870  0.894047  0.503307   
9566  0.511179 -0.919102  0.121639 -0.557549  0.261304  0.844749  0.014796   
9567  0.276868  0.470037  0.974904  0.802166  0.076656  0.220935  0.950438   

          RHRH        TV       TAP       TRH       VAP       VRH      APRH  
0     0.575511  1.844357 -1.925025 -1.121456 -1.624692 -0.946492  0.987889  
1     0.199739  0.088668  0.191253 -0.129166  0.203023 -0.137115 -0.295750  
2     0.140633  0.168395  0.114876 -0.149995  0.120918 -0.157884 -0.107706  
3     0.772792  2.099832 -1.078767 -1.381924 -0.916657 -1.174257  0.603262  
4     1.720877  1.560306 -0.885927 -1.830423 -0.709994 -1.466926  0.832907  
...        ...       ...       ...       ...       ...       ...       ...  
9563  1.379245  1.615941 -0.882694 -1.554711 -0.813913 -1.433564  0.783073  
9564  3.409019  0.943060  0.195882 -1.994113  0.158367 -1.612201 -0.334868  
9565  1.618968  0.589634 -0.442404  0.793454 -0.670806  1.203093 -0.902684  
9566  0.310861 -0.469826  0.062179 -0.285008 -0.111799  0.512445 -0.067820  
9567  0.643471  0.130138  0.269920  0.222094  0.458241  0.377048  0.782035  

[9568 rows x 14 columns]

In [11]:
traindf=data[0:7176]
testdf=data[7176:9568]
traindf,testdf

(            #T         V        AP        RH        TT            VV  \
 0    -1.478275 -1.247642  1.302211  0.758625  2.185296  1.556610e+00   
 1     0.289012  0.306798  0.661749 -0.446922  0.083528  9.412474e-02   
 2    -0.399976 -0.421013 -0.287207  0.375011  0.159980  1.772515e-01   
 3     1.572001  1.335770 -0.686238 -0.879086  2.471186  1.784283e+00   
 4    -1.395329 -1.118236  0.634923  1.311822  1.946942  1.250451e+00   
 ...        ...       ...       ...       ...       ...           ...   
 7171 -1.379274 -1.298620  1.488313  0.424928  1.902398  1.686413e+00   
 7172 -1.127761 -1.012358  1.406160 -0.778567  1.271844  1.024869e+00   
 7173  1.360622  1.180483 -0.654383 -0.583683  1.851292  1.393541e+00   
 7174 -0.436097  0.000929  0.784141 -0.659585  0.190181  8.632078e-07   
 7175  1.402095  0.607960 -0.431395 -1.731106  1.965870  3.696158e-01   
 
           APAP      RHRH        TV       TAP       TRH       VAP       VRH  \
 0     1.695753  0.575511  1.844357 -1.9250

In [12]:
traindf['EP']=trainy
traindf

<ipython-input-12-46c9e828cc85>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  traindf['EP']=trainy


#T         V        AP        RH        TT            VV  \
0    -1.478275 -1.247642  1.302211  0.758625  2.185296  1.556610e+00   
1     0.289012  0.306798  0.661749 -0.446922  0.083528  9.412474e-02   
2    -0.399976 -0.421013 -0.287207  0.375011  0.159980  1.772515e-01   
3     1.572001  1.335770 -0.686238 -0.879086  2.471186  1.784283e+00   
4    -1.395329 -1.118236  0.634923  1.311822  1.946942  1.250451e+00   
...        ...       ...       ...       ...       ...           ...   
7171 -1.379274 -1.298620  1.488313  0.424928  1.902398  1.686413e+00   
7172 -1.127761 -1.012358  1.406160 -0.778567  1.271844  1.024869e+00   
7173  1.360622  1.180483 -0.654383 -0.583683  1.851292  1.393541e+00   
7174 -0.436097  0.000929  0.784141 -0.659585  0.190181  8.632078e-07   
7175  1.402095  0.607960 -0.431395 -1.731106  1.965870  3.696158e-01   

          APAP      RHRH        TV       TAP       TRH       VAP       VRH  \
0     1.695753  0.575511  1.844357 -1.925025 -1.121456 -1.624692 -0.946492   
1     0.437912  0.199739  0.088668  0.191253 -0.129166  0.203023 -0.137115   
2     0.082488  0.140633  0.168395  0.114876 -0.149995  0.120918 -0.157884   
3     0.470923  0.772792  2.099832 -1.078767 -1.381924 -0.916657 -1.174257   
4     0.403128  1.720877  1.560306 -0.885927 -1.830423 -0.709994 -1.466926   
...        ...       ...       ...       ...       ...       ...       ...   
7171  2.215077  0.180564  1.791153 -2.052793 -0.586093 -1.932753 -0.551820   
7172  1.977286  0.606166  1.141698 -1.585812  0.878037 -1.423538  0.788188   
7173  0.428217  0.340685  1.606192 -0.890368 -0.794171 -0.772488 -0.689028   
7174  0.614877  0.435052 -0.000405 -0.341962  0.287643  0.000729 -0.000613   
7175  0.186102  2.996727  0.852418 -0.604857 -2.427175 -0.262271 -1.052444   

          APRH      EP  
0     0.987889  482.26  
1    -0.295750  446.94  
2    -0.107706  452.56  
3     0.603262  433.44  
4     0.832907  480.38  
...        ...     ...  
7171  0.632426  477.91  
7172 -1.094789  476.87  
7173  0.381952  437.65  
7174 -0.517208  459.97  
7175  0.746790  444.42  

[7176 rows x 15 columns]

In [13]:
testdf=testdf.reset_index(drop=True)
testdf

#T         V        AP        RH        TT        VV      APAP  \
0    -1.051800 -0.980329  0.739403  1.203540  1.106282  0.961046  0.546716   
1    -1.035547 -1.280899 -0.098504  0.568089  1.072357  1.640702  0.009703   
2     0.974385  1.640508 -1.298194  0.383580  0.949426  2.691266  1.685309   
3     0.117049 -1.179119 -1.291368 -0.779234  0.013700  1.390321  1.667632   
4    -0.397624 -1.364390 -0.217961 -0.307637  0.158105  1.861561  0.047507   
...        ...       ...       ...       ...       ...       ...       ...   
2387  1.323820  1.220665 -0.666778 -1.174413  1.752500  1.490023  0.444593   
2388  1.080028  0.873181  0.181367 -1.846353  1.166460  0.762446  0.032894   
2389  0.623595  0.945541 -0.709441  1.272387  0.388870  0.894047  0.503307   
2390  0.511179 -0.919102  0.121639 -0.557549  0.261304  0.844749  0.014796   
2391  0.276868  0.470037  0.974904  0.802166  0.076656  0.220935  0.950438   

          RHRH        TV       TAP       TRH       VAP       VRH      APRH  
0     1.448510  1.031110 -0.777704 -1.265883 -0.724858 -1.179866  0.889901  
1     0.322725  1.326431  0.102005 -0.588282  0.126173 -0.727664 -0.055959  
2     0.147134  1.598486 -1.264941  0.373755 -2.129698  0.629267 -0.497962  
3     0.607206 -0.138014 -0.151153 -0.091208  1.522677  0.918810  1.006279  
4     0.094641  0.542514  0.086666  0.122324  0.297384  0.419737  0.067053  
...        ...       ...       ...       ...       ...       ...       ...  
2387  1.379245  1.615941 -0.882694 -1.554711 -0.813913 -1.433564  0.783073  
2388  3.409019  0.943060  0.195882 -1.994113  0.158367 -1.612201 -0.334868  
2389  1.618968  0.589634 -0.442404  0.793454 -0.670806  1.203093 -0.902684  
2390  0.310861 -0.469826  0.062179 -0.285008 -0.111799  0.512445 -0.067820  
2391  0.643471  0.130138  0.269920  0.222094  0.458241  0.377048  0.782035  

[2392 rows x 14 columns]

In [14]:
trainp=traindf.to_numpy()
testnp=testdf.to_numpy()
trainp.shape,testnp.shape

((7176, 15), (2392, 14))

In [15]:
def cost(x,y,m):
    costval = 0
    N = x.shape[0]
    for i in range(N):
        costval +=(1/N)* ((y[i]-(m* x[i]).sum())**2)
    return float(costval)

In [16]:
def stepgrad(x,y,alpha,m):
    N=x.shape[0]
    updated_m=np.zeros(x.shape[1])
    for i in range(N):
        currin=x[i]
        currout=y[i]
        for j in range(x.shape[1]):
            updated_m[j] += (-2/N)*(currout-(m*currin).sum())*currin[j]
        newm=m-(alpha*updated_m)
    return newm

In [17]:
def gd(x,y,alpha,num):
    m=np.zeros(x.shape[1])
    for i in range(num):
        m=stepgrad(x,y,alpha,m)
        if i % 100== 0:
            print(i, "Cost= ", cost(x,y,m))
    print("Cost=", cost(x,y,m))
    return m

In [18]:
def run(trainp):
    x=trainp[:,:-1]
    x=x=np.append(x, np.ones(len(x)).reshape(-1, 1), axis=1)
    y=trainp[:,-1]
    alpha = 0.1
    num = 1500
    M = gd(x,y,alpha,num)
    return M

In [19]:
m=run(trainp)
print(m)

0 Cost=  158467.89251062152
100 Cost=  111.48732793286442
200 Cost=  30.565249642920843
300 Cost=  23.642596938533977
400 Cost=  21.11869395009111
500 Cost=  19.80272984596341
600 Cost=  19.091241070985667
700 Cost=  18.70514445868759
800 Cost=  18.495532218761287
900 Cost=  18.381726746812756
1000 Cost=  18.319937441362413
1100 Cost=  18.286389643718778
1200 Cost=  18.26817524689653
1300 Cost=  18.258285946147502
1400 Cost=  18.25291666213317
Cost= 18.25002268495323
[-1.35500428e+01 -3.73854039e+00  7.63456891e-01 -1.76935875e+00
  1.04134618e+00 -7.12610367e-02 -2.91957672e-01 -3.20454981e-01
  8.84879038e-01  3.99550972e-02 -5.12702558e-01  2.38470398e-01
 -3.77883091e-02 -3.39052287e-01  4.53187562e+02]


In [22]:
slopes=m
slopes

array([-1.35500428e+01, -3.73854039e+00,  7.63456891e-01, -1.76935875e+00,
        1.04134618e+00, -7.12610367e-02, -2.91957672e-01, -3.20454981e-01,
        8.84879038e-01,  3.99550972e-02, -5.12702558e-01,  2.38470398e-01,
       -3.77883091e-02, -3.39052287e-01,  4.53187562e+02])

In [24]:
m=slopes[0:-1]
c=slopes[-1]
m,c

(array([-13.55004283,  -3.73854039,   0.76345689,  -1.76935875,
          1.04134618,  -0.07126104,  -0.29195767,  -0.32045498,
          0.88487904,   0.0399551 ,  -0.51270256,   0.2384704 ,
         -0.03778831,  -0.33905229]),
 453.18756209528453)

In [25]:
def predict(dataval, m, c):
    N = dataval.shape[0]
    y = np.zeros(N)
    for i in range(N):                               #prediction using m ,c ,alpha and numof iterations 
        X = dataval[i,:]
        y[i] = (m * X).sum() + c
    return y

In [26]:
testpred=predict(testnp,m,c)
testpred,testpred.shape

(array([471.09959893, 473.37710554, 433.24889248, ..., 438.28333462,
        450.59434303, 446.42605542]),
 (2392,))

In [27]:
np.savetxt("cpp_prediction.csv", testpred,fmt='%f')